---

- name: Verify
  hosts: all

  tasks:
  
    - name: Check go version
      command: "go version"
      ignore_errors: yes
      register: golang_current_version

    - name: Ensure go is uninstalled
      assert:
        that:
          - golang_current_version.rc != 0