---

- name: Verify
  hosts: all

  tasks:
  
    - name: Check go version
      command: "go version"
      register: golang_current_version

    - name: Ensure go is installed
      assert:
        that:
          - golang_current_version.rc == 0
