---
name: Ansible Commit

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@main
    
    - name: Ansible Molecule Tests
      uses: gofrolist/molecule-action@v2
