---
name: Ansible Commit

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - uses: ansible/ansible-lint-action@main

  molecule:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: "${{ github.repository }}"
    - uses: gofrolist/molecule-action@v2
